from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from ..models.product import Category, Product, ProductImage


async def seed_database(db: AsyncSession):
    """Seed database with sample data"""

    # Check if data already exists
    result = await db.execute(select(Category))
    if result.scalars().first():
        return

    # Create categories
    categories = [
        Category(name="T-shirts", slug="t-shirts", description="Casual and comfortable t-shirts"),
        Category(name="Shorts", slug="shorts", description="Comfortable shorts for any occasion"),
        Category(name="Shirts", slug="shirts", description="Stylish shirts for every occasion"),
        Category(name="Jeans", slug="jeans", description="Classic denim jeans"),
        Category(name="Hoodie", slug="hoodie", description="Cozy hoodies for casual wear"),
    ]

    for cat in categories:
        db.add(cat)
    await db.commit()

    # Refresh to get IDs
    for cat in categories:
        await db.refresh(cat)

    cat_dict = {cat.slug: cat for cat in categories}

    # Sample products with real-looking data
    products_data = [
        {
            "name": "T-shirt with Tape Details",
            "slug": "t-shirt-tape-details",
            "description": "Classic cotton t-shirt featuring unique tape detail accents on the sleeves. Perfect for casual everyday wear.",
            "price": 120.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Black", "hex": "#000000"}, {"name": "White", "hex": "#FFFFFF"}, {"name": "Orange", "hex": "#F97316"}],
            "rating": 4.5,
            "reviews_count": 65,
            "stock": 50,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600"]
        },
        {
            "name": "Skinny Fit Jeans",
            "slug": "skinny-fit-jeans",
            "description": "Modern skinny fit jeans crafted from premium stretch denim. Comfortable all-day wear with a sleek silhouette.",
            "price": 260.00,
            "discount_price": 240.00,
            "discount_percent": 8,
            "category": "jeans",
            "sizes": ["28", "30", "32", "34", "36"],
            "colors": [{"name": "Blue", "hex": "#1E40AF"}, {"name": "Black", "hex": "#000000"}],
            "rating": 3.5,
            "reviews_count": 42,
            "stock": 35,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600"]
        },
        {
            "name": "Checkered Shirt",
            "slug": "checkered-shirt",
            "description": "Classic checkered pattern shirt made from soft cotton. Versatile piece that works for both casual and smart-casual occasions.",
            "price": 180.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Red", "hex": "#DC2626"}, {"name": "Blue", "hex": "#2563EB"}],
            "rating": 4.5,
            "reviews_count": 88,
            "stock": 42,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600"]
        },
        {
            "name": "Sleeve Striped T-shirt",
            "slug": "sleeve-striped-tshirt",
            "description": "Trendy t-shirt with distinctive striped sleeves. Made from premium cotton for ultimate comfort.",
            "price": 160.00,
            "discount_price": 130.00,
            "discount_percent": 19,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Orange", "hex": "#F97316"}, {"name": "Green", "hex": "#22C55E"}, {"name": "Navy", "hex": "#1E3A8A"}],
            "rating": 4.5,
            "reviews_count": 53,
            "stock": 28,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600"]
        },
        {
            "name": "Vertical Striped Shirt",
            "slug": "vertical-striped-shirt",
            "description": "Elegant vertical striped shirt perfect for both office and weekend wear. Premium fabric with excellent breathability.",
            "price": 232.00,
            "discount_price": 212.00,
            "discount_percent": 9,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Green", "hex": "#166534"}, {"name": "Blue", "hex": "#1D4ED8"}],
            "rating": 5.0,
            "reviews_count": 126,
            "stock": 55,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "formal",
            "images": ["https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600"]
        },
        {
            "name": "Courage Graphic T-shirt",
            "slug": "courage-graphic-tshirt",
            "description": "Bold graphic t-shirt with inspiring 'Courage' design. 100% organic cotton, soft and comfortable.",
            "price": 145.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Orange", "hex": "#EA580C"}, {"name": "Black", "hex": "#000000"}],
            "rating": 4.0,
            "reviews_count": 78,
            "stock": 60,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600"]
        },
        {
            "name": "Loose Fit Bermuda Shorts",
            "slug": "loose-fit-bermuda-shorts",
            "description": "Relaxed fit bermuda shorts ideal for summer days. Lightweight fabric with side pockets.",
            "price": 80.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shorts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Olive", "hex": "#84CC16"}, {"name": "Khaki", "hex": "#A3A380"}],
            "rating": 3.0,
            "reviews_count": 34,
            "stock": 45,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600"]
        },
        {
            "name": "Faded Skinny Jeans",
            "slug": "faded-skinny-jeans",
            "description": "Vintage-inspired faded skinny jeans with perfect stretch. Features distressed details for a worn-in look.",
            "price": 210.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "jeans",
            "sizes": ["28", "30", "32", "34"],
            "colors": [{"name": "Light Blue", "hex": "#60A5FA"}],
            "rating": 4.5,
            "reviews_count": 95,
            "stock": 30,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1475178626620-a4d074967452?w=600"]
        },
        {
            "name": "Classic Polo Shirt",
            "slug": "classic-polo-shirt",
            "description": "Timeless polo shirt crafted from pique cotton. Features ribbed collar and two-button placket.",
            "price": 135.00,
            "discount_price": 110.00,
            "discount_percent": 18,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Navy", "hex": "#1E3A8A"}, {"name": "White", "hex": "#FFFFFF"}, {"name": "Red", "hex": "#DC2626"}],
            "rating": 4.8,
            "reviews_count": 142,
            "stock": 75,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1625910513413-5fc45f05fd6b?w=600"]
        },
        {
            "name": "Premium Hoodie",
            "slug": "premium-hoodie",
            "description": "Ultra-soft premium hoodie with kangaroo pocket. Perfect for layering or wearing on its own.",
            "price": 195.00,
            "discount_price": 165.00,
            "discount_percent": 15,
            "category": "hoodie",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Gray", "hex": "#6B7280"}, {"name": "Black", "hex": "#000000"}, {"name": "Navy", "hex": "#1E3A8A"}],
            "rating": 4.7,
            "reviews_count": 210,
            "stock": 80,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600"]
        },
        {
            "name": "Denim Cargo Shorts",
            "slug": "denim-cargo-shorts",
            "description": "Rugged denim cargo shorts with multiple pockets. Built for comfort and durability.",
            "price": 95.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shorts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Blue", "hex": "#3B82F6"}, {"name": "Black", "hex": "#000000"}],
            "rating": 4.2,
            "reviews_count": 67,
            "stock": 40,
            "is_new_arrival": 0,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1560243563-062bfc001d68?w=600"]
        },
        {
            "name": "Formal White Shirt",
            "slug": "formal-white-shirt",
            "description": "Crisp white dress shirt with French cuffs. Perfect for business meetings and formal occasions.",
            "price": 220.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "White", "hex": "#FFFFFF"}],
            "rating": 4.9,
            "reviews_count": 189,
            "stock": 65,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "formal",
            "images": ["https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600"]
        },
        {
            "name": "Oversized Cotton T-shirt",
            "slug": "oversized-cotton-tshirt",
            "description": "Relaxed oversized fit t-shirt in premium heavyweight cotton. Street style essential.",
            "price": 89.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Black", "hex": "#000000"}, {"name": "Cream", "hex": "#FFFDD0"}],
            "rating": 4.6,
            "reviews_count": 234,
            "stock": 120,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600"]
        },
        {
            "name": "Slim Fit Chino Shorts",
            "slug": "slim-fit-chino-shorts",
            "description": "Classic chino shorts with a modern slim fit. Perfect for summer outings.",
            "price": 75.00,
            "discount_price": 60.00,
            "discount_percent": 20,
            "category": "shorts",
            "sizes": ["28", "30", "32", "34", "36"],
            "colors": [{"name": "Beige", "hex": "#D4C4A8"}, {"name": "Navy", "hex": "#1E3A8A"}],
            "rating": 4.3,
            "reviews_count": 89,
            "stock": 55,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600"]
        },
        {
            "name": "Vintage Wash Denim Jacket",
            "slug": "vintage-wash-denim-jacket",
            "description": "Classic denim jacket with vintage wash finish. Timeless style for layering.",
            "price": 289.00,
            "discount_price": 245.00,
            "discount_percent": 15,
            "category": "jeans",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Light Blue", "hex": "#87CEEB"}, {"name": "Dark Blue", "hex": "#00008B"}],
            "rating": 4.8,
            "reviews_count": 156,
            "stock": 40,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600"]
        },
        {
            "name": "Athletic Zip Hoodie",
            "slug": "athletic-zip-hoodie",
            "description": "Performance zip-up hoodie with moisture-wicking fabric. Ideal for workouts and casual wear.",
            "price": 165.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "hoodie",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Charcoal", "hex": "#36454F"}, {"name": "Heather Gray", "hex": "#9AA297"}],
            "rating": 4.5,
            "reviews_count": 178,
            "stock": 90,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "sporty",
            "images": ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600"]
        },
        {
            "name": "Linen Summer Shirt",
            "slug": "linen-summer-shirt",
            "description": "Breathable linen shirt perfect for hot summer days. Relaxed fit with button-down collar.",
            "price": 175.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "White", "hex": "#FFFFFF"}, {"name": "Sky Blue", "hex": "#87CEEB"}, {"name": "Sand", "hex": "#C2B280"}],
            "rating": 4.7,
            "reviews_count": 112,
            "stock": 65,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600"]
        },
        {
            "name": "Relaxed Fit Joggers",
            "slug": "relaxed-fit-joggers",
            "description": "Comfortable jogger pants with elastic waistband. Perfect for lounging or casual outings.",
            "price": 95.00,
            "discount_price": 80.00,
            "discount_percent": 16,
            "category": "shorts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Black", "hex": "#000000"}, {"name": "Gray", "hex": "#808080"}],
            "rating": 4.4,
            "reviews_count": 203,
            "stock": 110,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600"]
        },
        {
            "name": "Printed Beach Shirt",
            "slug": "printed-beach-shirt",
            "description": "Tropical print shirt for vacation vibes. Lightweight and breezy for beach days.",
            "price": 125.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Tropical", "hex": "#228B22"}],
            "rating": 4.2,
            "reviews_count": 67,
            "stock": 45,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600"]
        },
        {
            "name": "Essential Crewneck Sweatshirt",
            "slug": "essential-crewneck-sweatshirt",
            "description": "Classic crewneck sweatshirt in soft fleece. Everyday essential for cooler days.",
            "price": 115.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "hoodie",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Navy", "hex": "#1E3A8A"}, {"name": "Forest Green", "hex": "#228B22"}, {"name": "Burgundy", "hex": "#800020"}],
            "rating": 4.6,
            "reviews_count": 289,
            "stock": 150,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600"]
        },
        {
            "name": "Straight Leg Jeans",
            "slug": "straight-leg-jeans",
            "description": "Classic straight leg jeans in dark wash. Versatile staple for any wardrobe.",
            "price": 185.00,
            "discount_price": 155.00,
            "discount_percent": 16,
            "category": "jeans",
            "sizes": ["28", "30", "32", "34", "36"],
            "colors": [{"name": "Dark Indigo", "hex": "#091F5B"}],
            "rating": 4.5,
            "reviews_count": 312,
            "stock": 85,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600"]
        },
        {
            "name": "Henley Long Sleeve",
            "slug": "henley-long-sleeve",
            "description": "Classic henley with three-button placket. Soft cotton blend for all-day comfort.",
            "price": 78.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Charcoal", "hex": "#36454F"}, {"name": "Olive", "hex": "#808000"}, {"name": "White", "hex": "#FFFFFF"}],
            "rating": 4.4,
            "reviews_count": 145,
            "stock": 70,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600"]
        },
        {
            "name": "Cargo Pants",
            "slug": "cargo-pants",
            "description": "Utility-inspired cargo pants with multiple pockets. Durable cotton twill construction.",
            "price": 145.00,
            "discount_price": 120.00,
            "discount_percent": 17,
            "category": "jeans",
            "sizes": ["28", "30", "32", "34", "36"],
            "colors": [{"name": "Khaki", "hex": "#C3B091"}, {"name": "Olive", "hex": "#808000"}, {"name": "Black", "hex": "#000000"}],
            "rating": 4.3,
            "reviews_count": 178,
            "stock": 60,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=600"]
        },
        {
            "name": "Performance Tank Top",
            "slug": "performance-tank-top",
            "description": "Breathable tank top for workouts. Quick-dry fabric keeps you cool during intense sessions.",
            "price": 45.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "t-shirts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Black", "hex": "#000000"}, {"name": "White", "hex": "#FFFFFF"}, {"name": "Red", "hex": "#FF0000"}],
            "rating": 4.1,
            "reviews_count": 92,
            "stock": 100,
            "is_new_arrival": 0,
            "is_top_selling": 0,
            "style": "sporty",
            "images": ["https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600"]
        },
        {
            "name": "Fleece Pullover Hoodie",
            "slug": "fleece-pullover-hoodie",
            "description": "Cozy fleece pullover hoodie with front pocket. Perfect for layering in cold weather.",
            "price": 135.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "hoodie",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Heather Gray", "hex": "#9AA297"}, {"name": "Navy", "hex": "#1E3A8A"}],
            "rating": 4.7,
            "reviews_count": 267,
            "stock": 95,
            "is_new_arrival": 1,
            "is_top_selling": 1,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600"]
        },
        {
            "name": "Oxford Button-Down",
            "slug": "oxford-button-down",
            "description": "Classic oxford cloth button-down shirt. Timeless style that works from office to weekend.",
            "price": 165.00,
            "discount_price": 140.00,
            "discount_percent": 15,
            "category": "shirts",
            "sizes": ["S", "M", "L", "XL", "XXL"],
            "colors": [{"name": "Light Blue", "hex": "#ADD8E6"}, {"name": "White", "hex": "#FFFFFF"}, {"name": "Pink", "hex": "#FFC0CB"}],
            "rating": 4.8,
            "reviews_count": 345,
            "stock": 120,
            "is_new_arrival": 0,
            "is_top_selling": 1,
            "style": "formal",
            "images": ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600"]
        },
        {
            "name": "Swimming Trunks",
            "slug": "swimming-trunks",
            "description": "Quick-dry swimming trunks with mesh lining. Elastic waist for comfortable fit.",
            "price": 55.00,
            "discount_price": None,
            "discount_percent": None,
            "category": "shorts",
            "sizes": ["S", "M", "L", "XL"],
            "colors": [{"name": "Blue", "hex": "#0000FF"}, {"name": "Tropical", "hex": "#00CED1"}],
            "rating": 4.2,
            "reviews_count": 156,
            "stock": 80,
            "is_new_arrival": 1,
            "is_top_selling": 0,
            "style": "casual",
            "images": ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600"]
        },
    ]

    for p_data in products_data:
        category = cat_dict.get(p_data.pop("category"))
        images_urls = p_data.pop("images")

        product = Product(
            **p_data,
            category_id=category.id if category else None
        )
        db.add(product)
        await db.commit()
        await db.refresh(product)

        for i, url in enumerate(images_urls):
            img = ProductImage(
                product_id=product.id,
                url=url,
                is_primary=1 if i == 0 else 0,
                sort_order=i
            )
            db.add(img)

    await db.commit()
    print("Database seeded successfully!")
